# permissions to do viewer playerstats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playerstats-viewer-role
rules:
- apiGroups:
  - fantasy.jogabonito.io
  resources:
  - playerstats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fantasy.jogabonito.io
  resources:
  - playerstats/status
  verbs:
  - get
