# permissions to do edit playerstats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: playerstats-editor-role
rules:
- apiGroups:
  - fantasy.jogabonito.io
  resources:
  - playerstats
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fantasy.jogabonito.io
  resources:
  - playerstats/status
  verbs:
  - get
  - patch
  - update
